INSERT into shop.customers(customer_name, address, vip) VALUES ('vera','london',true),
                                                               ('anna','munich',false),
                                                               ('irina','spb',true),
                                                               ('elena','spb',false),
                                                               ('julia','london',false);
INSERT into shop.items(item_name, category, price, available) VALUES ('apples','fruits',5, 10000),
                                                                     ('oranges','fruits',7, 10000),
                                                                     ('mango','fruits',15, 5000),
                                                                     ('tomato','vegetables',5, 10000),
                                                                     ('onion','vegetables',2, 10000),
                                                                     ('potato','vegetables',1, 10000),
                                                                     ('milk','dairy',3, 10000),
                                                                     ('cream fresh','dairy',20, 100),
                                                                     ('cheddar','dairy',25, 1000),
                                                                     ('camembert','dairy',30, 1000),
                                                                     ('cottage cheese','dairy',5, 5000),
                                                                     ('bread','bakery',2,10000),
                                                                     ('baguette','bakery',3,10000),
                                                                     ('cake','bakery',5,1000),
                                                                     ('cookies','bakery',5,10000);

